---
dist: xenial
language: python
python: "3.6"

sudo: true

env:
  - test_os: debian9

install:
  # Cloning testing template
  - sudo mkdir /etc/ansible
  - sudo chown -R "${USER}:" /etc/ansible
  - git clone https://github.com/Nani-o/ansible-template-role-test /etc/ansible

script:
  # Run tests.
  - bash /etc/ansible/test.sh
