---
- name: Create config dir
  file:
    path: "{{ hass_config_dir }}"
    state: directory
    owner: "{{ hass_user }}"
    group: "{{ hass_user }}"

- name: Deploy secrets
  template:
    src: secrets.yaml.j2
    dest: "{{ hass_config_dir }}/secrets.yaml"
    owner: "{{ hass_user }}"
    group: "{{ hass_user }}"
    mode: 0600
  no_log: true
  notify:
    - restart homeassistant
  when: "hass_config_secrets is defined"

- block:
    - name: Deploy pulling script
      copy:
        src: pull_config.sh
        dest: "{{ hass_config_dir }}/"
        owner: "{{ hass_user }}"
        group: "{{ hass_user }}"
        mode: 0755

    - name: Execute the pulling script
      shell: "{{ hass_config_dir }}/pull_config.sh {{ hass_config_git_url }}"
      changed_when: false
      become: yes
      become_user: "{{ hass_user }}"

    - name: Setup a cron job
      cron:
        job: "{{ hass_config_dir }}/pull_config.sh {{ hass_config_git_url }}"
        name: Pull homeassistant config from repo
        minute: "*/5"
        user: "{{ hass_user }}"
  when: "hass_config_git_url is defined"

- block:
    - name: Make sure custom components folder exists
      file:
        path: "{{ hass_config_dir }}/custom_components"
        owner: "{{ hass_user }}"
        group: "{{ hass_user }}"
        mode: 0755
        state: directory

    - name: Deploy custom updater component
      get_url:
        url: https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py
        dest: "{{ hass_config_dir }}/custom_components/custom_updater.py"
        owner: "{{ hass_user }}"
        group: "{{ hass_user }}"
        mode: 0644
      notify:
        - restart homeassistant
  when: "hass_install_custom_updater is True"
...
