---
- name: Installing dependencies
  apt:
    name:
      - libavahi-compat-libdnssd-dev
      - libffi-dev
      - libssl-dev
      - python3-pip
      - python3-venv
    state: latest
    update_cache: yes

- name: Install dependencies for scripts
  pip:
    name:
      - python-gilt
      - plexapi
    state: latest

- name: Create an user for Home Assistant
  user:
    name: "{{ hass_user }}"
    state: present
    home: "{{ hass_user_home }}"

- name: Installing requirements in a virtualenv
  pip:
    name:
      - wheel
      - colorlog
    state: latest
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: "{{ hass_venv_dir }}"
  become: yes
  become_user: "{{ hass_user }}"

- name: Installing homeassistant in a virtualenv
  pip:
    name: homeassistant
    state: latest
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: "{{ hass_venv_dir }}"
  become: yes
  become_user: "{{ hass_user }}"
  notify:
    - restart homeassistant

- name: Installing systemd service
  template:
    src: homeassistant.service.j2
    dest: /etc/systemd/system/homeassistant.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon-reload
    - restart homeassistant

- name: Add sudo permissions allowing hass_user to restart service
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^{{ hass_user }}"
    line: "{{ hass_user }} ALL= NOPASSWD: /bin/systemctl * homeassistant*"
    state: present
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
...
